### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arefeena** [Edresson/VoiceSplit#2]
Does this repository have a license? 

If not, can I suggest using the same [license as MINDsLab's VoiceFilter implementation](https://github.com/mindslab-ai/voicefilter#license) (Apache License 2.0) or similar?

**Comment by Edresson** [comment]
Thank you I forgot to add the license. Apache 2 license was added to the commit 4f65a25ae119e6dc5cfd1f1456b66465a5412c3d
