### ISSUE TITLE
'numpy.ndarray' object has no attribute 'unsqueeze'

### ISSUE THREAD

**Issue by abcxyz-ai** [Edresson/VoiceSplit#3]
I am trying to run Colab notebooks Demo of experiment 5 and i could not find a way to resolve following error that occurs in function predict.
     
     29   mixed_spec = mixed_spec.unsqueeze(0)
     30   embedding = embedding.unsqueeze(0)
     31 

AttributeError: 'numpy.ndarray' object has no attribute 'unsqueeze' 

Could you please help me. Thanks in advance.

**Comment by Edresson** [comment]
Please convert the mixed_spec and embedding to torch tensor. Example: mixed_spec = torch.from_numpy(mixed_spec).unsqueeze(0)
