### ISSUE TITLE
two ways of calculating spectrogram used in audio.wav2spec()

### ISSUE THREAD

**Issue by iPwnXX** [Edresson/VoiceSplit#5]
In `audio_processor.py` `class openVoiceFilterAudioProcessor`  the function `wav2spec(self, y)` first use torchaudio to calculate spectrogram (which not seems to be used), then use librosa.stft to calculate spectrogram again and return this result.
why to do this twice?

**Comment by Edresson** [comment]
Thanks, It's a bug. I was doing a speeds test, and forget to comment the torchaudio spectrogram calculation. Bug solved with my latest commit :).
