### ISSUE TITLE
 Mixture of same-sex speakers

### ISSUE THREAD

**Issue by ujscjj** [Edresson/VoiceSplit#6]
Hi, thank you for your sharing.
It seems that this method is difficult to separate the mixture of same-sex speakers. Did you encounter such a problem in the test?

**Comment by Edresson** [comment]
Hi, I don't remember :/. One thing that can be done is to train the model with a better speaker encoder like [H/ASP](https://arxiv.org/abs/2009.14153) (https://github.com/clovaai/voxceleb_trainer) this should greatly improve the results of the model. Also, it might be interesting to ensure that the model is trained with more mixed samples from same-sex talkers

**Comment by ujscjj** [comment]
ok, thanks. Happy day.
