### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by YaFanYen** [Edresson/VoiceSplit#7]
https://github.com/Edresson/VoiceSplit/blob/03b60c0e00e1b7b6a9ffd87cf3c17d9d4a0a3a9d/train.py#L108

Hi, @Edresson 
I'm wondering if the code in line 108 in `train.py` is wrong?
Since the function SiSNR_With_Pit in `generic_utils.py` gets input with `source, estimate source, source lengths`
but line 108 in train.py feeds `estimate source, source, source lengths`

**Comment by Edresson** [comment]
Hi @YaFanYen,
Thanks for reporting this issue,
I think that it will not influence a lot the final results but it is good to keep the standard.
The commit 43d036fb67094020a911b6feca178f4bc3f40a16  fix this issue.
